#!/bin/bash
#
# v1.0.0
#
if [[ ( "$1" == "?" )  || ( "$1" == "h" ) ]]
then
    echo "
    Documentation
	Redémarre adb

	Syntaxe:" $0 " -to
        t: Affiche les commandes executées
        o: Optien
	"

   exit 1
fi

if [[ $1 == "-"*'t'* ]]
then
    set -x #echo on
fi

if [[ $1 == "-"*"o"* ]]
then
    #Traitement option -o
fi

pkill -f adb
adb start-server
flutter devices

exit 0
