#!/bin/bash

# Vérifie que jq est installé
if ! command -v jq &> /dev/null; then
  echo "❌ Erreur : 'jq' n'est pas installé. Installe-le avec : sudo apt install jq"
  exit 1
fi

# Relance adb pour éliminer tous zombies
adb kill-server
adb start-server
adb devices

# Récupère les 2 premiers IDs des devices Android (arm et arm64)
devices=($(flutter devices --machine | jq -r '.[] | select(.targetPlatform == "android-arm" or .targetPlatform == "android-arm64") | .id'))

if [ ${#devices[@]} -lt 2 ]; then
  echo "❌ Moins de 2 appareils détectés. Branche-les puis réessaie."
  flutter devices
  exit 1
fi


echo "✅ App lancement sur les 2 appareils."

# Ouvre Konsole avec un onglet par device pour logs adb logcat
I=0
WIDTH=20
HEIGHT=10
XOFFSET=0
for device in "${devices[@]:0:2}"; do
	echo "lancement $device"
	YOFFSET=$((600*I))
	((I++))

	konsole -e bash -c "flutter run -d $device --no-hot; echo 'Terminé — appuyez sur q pour quitter'; while true; do read -n 1 key; if [[ \$key == q ]]; then break; fi; done" &
#	konsole --new-tab -e bash -c "flutter run -d $device;" &
done

