import 'package:flutter/material.dart';

enum BonusType { none, doubleLetter, tripleLetter, doubleWord, tripleWord }

const List<List<BonusType>> bonusMap = [
  [
    BonusType.tripleWord,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.tripleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.tripleWord,
  ],
  [
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.tripleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.tripleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
  ],
  [
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
  ],
  [
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
  ],
  [
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.none,
  ],
  [
    BonusType.none,
    BonusType.tripleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.tripleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.tripleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.tripleLetter,
    BonusType.none,
  ],
  [
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
  ],
  [
    BonusType.tripleWord,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.tripleWord,
  ],
  [
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
  ],
  [
    BonusType.none,
    BonusType.tripleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.tripleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.tripleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.tripleLetter,
    BonusType.none,
  ],
  [
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.none,
  ],
  [
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
  ],
  [
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
  ],
  [
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.tripleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.tripleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleWord,
    BonusType.none,
  ],
  [
    BonusType.tripleWord,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.tripleWord,
    BonusType.none,
    BonusType.none,
    BonusType.none,
    BonusType.doubleLetter,
    BonusType.none,
    BonusType.none,
    BonusType.tripleWord,
  ],
];

Color getColorForBonus(BonusType bonus) {
  switch (bonus) {
    case BonusType.doubleLetter:
      return const Color(0xFF76B8CC);
    case BonusType.tripleLetter:
      return const Color(0xFF0F427D);
    case BonusType.doubleWord:
      return const Color(0xFFE3A798);
    case BonusType.tripleWord:
      return const Color(0xFFAB0401);
    case BonusType.none:
      return const Color(0xFFCAC5AD);
  }
}

String bonusLabel(BonusType bonus) {
  switch (bonus) {
    case BonusType.doubleLetter:
      return "LD";
    case BonusType.tripleLetter:
      return "LT";
    case BonusType.doubleWord:
      return "MD";
    case BonusType.tripleWord:
      return "MT";
    default:
      return "";
  }
}
